<?php

namespace Database\Seeders;

use App\Models\RfpForm;
use Illuminate\Database\Seeder;

class RfpFormSeeder extends Seeder
{
    public function run(): void
    {
        $forms = [
            ['code' => '001', 'description' => 'REPRESENTATION EXPENSES'],
            ['code' => '002', 'description' => 'SALES INVOICE'],
            ['code' => '003', 'description' => 'REPAIRS AND MAINTENANCE'],
            ['code' => '004', 'description' => 'PADCAL EMPLOYEE CASH ADVANCE'],
            ['code' => '005', 'description' => 'APPRAISAL OF PROPERTY'],
            ['code' => '006', 'description' => 'PLANE FARE'],
            ['code' => '007', 'description' => 'FUNERAL ASSISTANCE'],
            ['code' => '008', 'description' => 'TRAVEL ALLOWANCE'],
            ['code' => '009', 'description' => 'BULAWAN EMPLOYEES CASH ADVANCE'],
            ['code' => '010', 'description' => 'MONEY DEPOSITED FOR'],
            ['code' => '011', 'description' => 'JANITORIAL SERVICES'],
            ['code' => '012', 'description' => 'MTI - TRUST FEE'],
            ['code' => '013', 'description' => 'FINAL PAYMENT TO CONSIGNMENT'],
            ['code' => '014', 'description' => 'REPAIR AND MAINTENANCE'],
            ['code' => '015', 'description' => 'SCRAP SALE'],
            ['code' => '016', 'description' => 'SOFTWARE SUPPORT CHARGES'],
            ['code' => '017', 'description' => 'REPLACEMENT OF STALE CHECK'],
            ['code' => '018', 'description' => 'CUSTOM DUTIES, TAXES'],
            ['code' => '019', 'description' => 'COURIER SERVICES'],
            ['code' => '020', 'description' => 'CASH GIFT'],
            ['code' => '021', 'description' => 'RETIREMENT GRATUITY PAY'],
            ['code' => '022', 'description' => 'FILING FEE'],
            ['code' => '023', 'description' => 'REGISTRATION FEE'],
            ['code' => '024', 'description' => 'OVERTIME PAY'],
            ['code' => '025', 'description' => 'PER DIEM'],
            ['code' => '026', 'description' => 'THE CHAMPAGNE EDITION CONDOMINIUM C'],
            ['code' => '027', 'description' => 'ONE-TIME FINANCIAL ASSISTANCE'],
            ['code' => '028', 'description' => 'CAR PLAN / CAR LOAN'],
            ['code' => '029', 'description' => 'REGISTRY OF DEEDS'],
            ['code' => '030', 'description' => 'TRANSPORTATION ALLOWANCE INDENT'],
            ['code' => '031', 'description' => 'HOSPITAL BILLS'],
            ['code' => '032', 'description' => 'ROYALTY AGREEMENT'],
            ['code' => '033', 'description' => 'ARRANGER\'S FEE'],
            ['code' => '034', 'description' => 'ADVANCES TO CONTRACTOR'],
            ['code' => '035', 'description' => 'COMMITMENT FEE'],
            ['code' => '036', 'description' => 'PURCHASE OF BOOK'],
            ['code' => '037', 'description' => 'ADVANCES TO ANGLO AMERICAN'],
            ['code' => '038', 'description' => 'PRINTING OF ANNUAL/INTERIM REPORT'],
            ['code' => '039', 'description' => 'REAL PROPERTY TAX'],
            ['code' => '040', 'description' => 'FORFEITURE OF DISCOUNT'],
            ['code' => '041', 'description' => 'RECEIVABLE AGAINST FOUNDATION'],
            ['code' => '042', 'description' => 'DEED OF ASSIGNMENT'],
            ['code' => '043', 'description' => 'CBA NEGOTIATIONS'],
            ['code' => '044', 'description' => 'FULL PAYMENT OF MATURITY LOAN'],
            ['code' => '045', 'description' => 'REIMBURSEMENT OF EXP./ROYALTIES'],
            ['code' => '046', 'description' => 'PROGRESS BILLING'],
            ['code' => '047', 'description' => 'TOWING SERVICES'],
            ['code' => '048', 'description' => 'ACCEPTANCE FEE'],
            ['code' => '049', 'description' => 'UPDATE SERVICE AGREEMENT'],
            ['code' => '050', 'description' => 'PAYMENT TO DAMAGE VEHICLE'],
            ['code' => '051', 'description' => 'DIRECTORS BONUS'],
            ['code' => '052', 'description' => 'SUMMER OUTING'],
            ['code' => '053', 'description' => 'REIM./BROKE CHARGES FOR'],
            ['code' => '054', 'description' => 'PHILIPPINE STOCK EXCHANGE, INC.'],
            ['code' => '055', 'description' => 'REIM./BROKERAGE CHARGES'],
            ['code' => '056', 'description' => 'PAYMENT OF INTEREST FROM LOAN'],
            ['code' => '057', 'description' => 'BOND'],
            ['code' => '058', 'description' => 'RENTAL FEE'],
            ['code' => '059', 'description' => 'CU CONCS SHIPMENT EXPENSES'],
            ['code' => '060', 'description' => 'FREIGHT CHARGES'],
            ['code' => '061', 'description' => 'TRAVEL EXPENSE OF GHB'],
            ['code' => '062', 'description' => 'UMPIRE ANALYSIS'],
            ['code' => '063', 'description' => 'SUBSCRIPTION SHARE AT PAR VALUE'],
            ['code' => '064', 'description' => 'ESCROW FEES'],
            ['code' => '065', 'description' => 'SENIORITY PAY'],
            ['code' => '066', 'description' => 'LOAN AMORTIZATION ON MTL'],
            ['code' => '067', 'description' => 'ISSUANCE FEE'],
            ['code' => '068', 'description' => 'LICENSE FEE'],
            ['code' => '069', 'description' => 'PHILEX RETIREMENT TRUST'],
            ['code' => '070', 'description' => 'BOWLING TOURNAMENT'],
            ['code' => '071', 'description' => 'TRAVEL EXPENSE OF GHB'],
            ['code' => '072', 'description' => 'BANK CHARGES ON LOANS'],
            ['code' => '073', 'description' => 'ADDITIONAL BENEFITS'],
            ['code' => '074', 'description' => 'TRAINING FEE'],
            ['code' => '075', 'description' => 'CONTRACT SALARY'],
            ['code' => '076', 'description' => 'PARTNERS SHARE'],
            ['code' => '077', 'description' => 'BSI INSPECTORATE LIMITED'],
            ['code' => '078', 'description' => 'ADVANCE MONTHLY CHECK PAYMENTS'],
            ['code' => '079', 'description' => 'MONTHLY CAR AMORTIZATION'],
            ['code' => '080', 'description' => '($) PHILEX INSURANCE AGENCY'],
            ['code' => '081', 'description' => 'HONORARIUM'],
            ['code' => '082', 'description' => 'TAX DEFICIENCY'],
            ['code' => '083', 'description' => 'TAX LIABILITY'],
            ['code' => '084', 'description' => 'AGENCY COMMISSION'],
            ['code' => '085', 'description' => '$ OUT OF POCKET EXPENSES'],
            ['code' => '086', 'description' => '$ RETAINER FEE'],
            ['code' => '087', 'description' => 'SALE OF USE EQUIPMENT'],
            ['code' => '088', 'description' => 'PURCHASE OF TRANSPORTATION EQUIPMEN'],
            ['code' => '089', 'description' => 'MANPOWER SERVICES'],
            ['code' => '090', 'description' => 'ESTABLISHMENT FEE'],
            ['code' => '091', 'description' => 'LITIGATION EXPENSES'],
            ['code' => '092', 'description' => 'INVESTMENT IN SHARES'],
            ['code' => '093', 'description' => 'MONEY MARKET PLACEMENT'],
            ['code' => '094', 'description' => 'DOCUMENTARY STAMP TAX FEE'],
            ['code' => '095', 'description' => 'PAYMENT MADE TO INVOICE'],
            ['code' => '096', 'description' => 'CONVERSION OF US$ TO PESO'],
            ['code' => '097', 'description' => 'PURCHASE OF SERVICE CAR'],
            ['code' => '098', 'description' => 'RENEWAL FEE'],
            ['code' => '099', 'description' => 'PAYMENT OF SUBSCRIPTION PAYABLE'],
            ['code' => '100', 'description' => 'FRONT-END MONEY'],
            ['code' => '101', 'description' => 'VISA FEE'],
            ['code' => '102', 'description' => 'OB MONEY'],
            ['code' => '103', 'description' => 'DIVIDEND PAYMENT'],
            ['code' => '104', 'description' => 'PGI ACCOUNT'],
            ['code' => '105', 'description' => 'PURCHASE OF PHILEX SHARES'],
            ['code' => '106', 'description' => 'VISA APPLICATION'],
            ['code' => '107', 'description' => 'MPSA SHARING'],
            ['code' => '108', 'description' => 'LASCOGON FUNDING'],
            ['code' => '109', 'description' => 'SHARES BUYBACK'],
            ['code' => '110', 'description' => 'ROYALTIES - ITF/ICC'],
            ['code' => '111', 'description' => 'OTHERS'],
            ['code' => '112', 'description' => 'CASH ADVANCE FOR LIQUIDATION'],
            ['code' => '113', 'description' => 'LAND BANKING PROJECT'],
            ['code' => '114', 'description' => 'IOU - COMREL'],
            ['code' => '115', 'description' => 'REPLENISHMENT OF COMREL FUND'],
            ['code' => '116', 'description' => 'ADVANCES'],
            ['code' => '117', 'description' => 'CAPITAL GAINS TAX'],
            ['code' => '118', 'description' => 'SEPARATION PAY'],
            ['code' => '119', 'description' => 'OFFICE RELOCATION'],
            ['code' => '120', 'description' => 'BUSINESS PROCESS REVIEW'],
            ['code' => '121', 'description' => 'ACCIDENT BENEFIT INSURANCE'],
            ['code' => '122', 'description' => 'FINAL CLAIM'],
            ['code' => '123', 'description' => 'GOLD BULLION SHIPMENT EXPENSES'],
            ['code' => '124', 'description' => 'BUSINESS PERMIT'],
            ['code' => '125', 'description' => 'BUSIESS MEETINGS'],
            ['code' => 'ADS', 'description' => 'NEWSPAPER ADVERTISEMENT'],
            ['code' => 'ADV', 'description' => 'ADVANCES TO SUPPLIER'],
            ['code' => 'ALL', 'description' => 'MEAL ALLOWANCE'],
            ['code' => 'ALT', 'description' => 'ALLOTMENT'],
            ['code' => 'AMR', 'description' => 'ADVANCE MONTHLY ROYALTIES'],
            ['code' => 'ASN', 'description' => 'ASSOCIATION DUES'],
            ['code' => 'BEN', 'description' => 'PHILEX MATERNITY BENEFIT'],
            ['code' => 'BIL', 'description' => 'OTHER BILLING'],
            ['code' => 'BRO', 'description' => 'BROKERAGE CHARGES'],
            ['code' => 'BSA', 'description' => 'SECURITY ALLOWANCE'],
            ['code' => 'CAN', 'description' => 'CANTEEN'],
            ['code' => 'CAS', 'description' => 'CASH PURCHASE'],
            ['code' => 'CNP', 'description' => 'CONTRACTUALS\' PAYROLL'],
            ['code' => 'COM', 'description' => 'COMMUNICATION-RELATED SERVICES'],
            ['code' => 'CON', 'description' => 'CONSULTANCY'],
            ['code' => 'COO', 'description' => 'PHILEX CREDIT COOPERATIVE INC.'],
            ['code' => 'CRE', 'description' => 'CREDIT CARD PAYMENT'],
            ['code' => 'DEA', 'description' => 'DEATH CLAIMS'],
            ['code' => 'DON', 'description' => 'DONATIONS'],
            ['code' => 'EDU', 'description' => 'EDUCATIONAL ASSISTANCE'],
            ['code' => 'FED', 'description' => 'CONSULTANCY'],
            ['code' => 'FEE', 'description' => 'RETAINER FEE'],
            ['code' => 'FID', 'description' => 'FIDELITY STOCK TRANSFER SERVICES'],
            ['code' => 'FIL', 'description' => 'FILING AND RESEARCH FEE'],
            ['code' => 'FIN', 'description' => 'FINAL PAY'],
            ['code' => 'FOR', 'description' => 'FORWARDING CHARGES'],
            ['code' => 'FTR', 'description' => 'FUND TRANSFER'],
            ['code' => 'GOV', 'description' => 'SSS,BIR,HDMF & OTHER GOV\'T. OFFICE'],
            ['code' => 'HTL', 'description' => 'HOTEL ACCOMODATION AND OTHERS'],
            ['code' => 'IND', 'description' => 'SUBSCRIPTIONS & MEMBERSHIP DUES'],
            ['code' => 'INS', 'description' => 'INSURANCE PREMIUM'],
            ['code' => 'IPO', 'description' => 'PAYMENTS MADE TO IPO'],
            ['code' => 'LEG', 'description' => 'LEGAL FEES'],
            ['code' => 'LOC', 'description' => 'SUBSCRIPTIONS & MEMBERSHIP DUES'],
            ['code' => 'LPO', 'description' => 'PAYMENTS MADE TO LPO'],
            ['code' => 'MAT', 'description' => 'SSS MATERNITY & SICKNESS BENEFIT'],
            ['code' => 'MED', 'description' => 'MEDICINE REIMBURSEMENT'],
            ['code' => 'MIN', 'description' => 'MINE WASTE AND TAILINGS FEE'],
            ['code' => 'MIS', 'description' => 'MISCELLANEOUS EXPENSES'],
            ['code' => 'MON', 'description' => 'CONTRIBUTION'],
            ['code' => 'NOT', 'description' => 'NOTARIAL FEES'],
            ['code' => 'OCC', 'description' => 'OCCUPATION FEE'],
            ['code' => 'OTH', 'description' => 'DIRECTOR\'S FEE'],
            ['code' => 'PAY', 'description' => 'MONTHLY PAYROLL'],
            ['code' => 'PCO', 'description' => 'PAYMENT TO CONTRACTS'],
            ['code' => 'PET', 'description' => 'PASIG PETRON'],
            ['code' => 'PHI', 'description' => 'PHILEX INSURANCE'],
            ['code' => 'PHS', 'description' => 'PHILAM CARE HEALTH SYSTEMS INC.'],
            ['code' => 'PII', 'description' => 'PAYMENT TO INDENT INVOICE WITH IPO'],
            ['code' => 'PRO', 'description' => 'PROFESSIONAL SERVICES'],
            ['code' => 'RCE', 'description' => 'RICE SUBSIDY'],
            ['code' => 'REF', 'description' => 'REFUND'],
            ['code' => 'REP', 'description' => 'REPLENISHMENT OF PETTY CASH FUND'],
            ['code' => 'REV', 'description' => 'REVOLVING FUND'],
            ['code' => 'ROY', 'description' => 'ROYALTIES'],
            ['code' => 'SA', 'description' => 'XXX'],
            ['code' => 'SEC', 'description' => 'SECURITY SERVICES'],
            ['code' => 'SEM', 'description' => 'SEMINARS/TRAINING FEE'],
            ['code' => 'SER', 'description' => 'OTHER SERVICES'],
            ['code' => 'STF', 'description' => 'SERVICE AND TECHNICAL FEES'],
            ['code' => 'STL', 'description' => 'STALE CHECK(DIVIDEND PAYMENT ONLY)'],
            ['code' => 'SUB', 'description' => 'SUBSCRIPTIONS & MEMBERSHIP DUES'],
            ['code' => 'TSF', 'description' => 'SERVICE AND TECHNICAL FEE'],
            ['code' => 'UNI', 'description' => 'UNION'],
            ['code' => 'UTL', 'description' => 'MERALCO, MWSS, TELEPHONE BILLS'],
            ['code' => 'XER', 'description' => 'REPRODUCTION COSTS'],
        ];

        foreach ($forms as $form) {
            RfpForm::create($form);
        }
    }
}
