<?php

namespace Database\Seeders;

use App\Models\SharedDescription;
use Illuminate\Database\Seeder;

class SharedDescriptionSeeder extends Seeder
{
    public function run(): void
    {
        $descriptions = [
            ['code' => '001', 'description' => 'CASH ADVANCE RE:OB TRIP TO'],
            ['code' => '002', 'description' => 'PROJECT FUNDS FOR'],
            ['code' => '003', 'description' => 'REPLENISHMENT OF REVOLVING FUND.'],
            ['code' => '004', 'description' => 'REPLENISHMENT OF PETTY CASH FUND.'],
            ['code' => '005', 'description' => 'REPAIRS & MAINTENANCE'],
            ['code' => '006', 'description' => 'CASH ADVANCE AGAINST PCF.'],
            ['code' => '007', 'description' => 'OFFICE SUPPLIES'],
            ['code' => '008', 'description' => 'C.O.D. PURCHASE FOR PO NO.'],
            ['code' => '009', 'description' => 'PROVISIONS FOR'],
            ['code' => '010', 'description' => 'PUBLICATION FEE.'],
            ['code' => '011', 'description' => 'PROCESSING FEE.'],
            ['code' => '012', 'description' => 'PAYM\'T TO SUPPLIER INV. NO.'],
            ['code' => '013', 'description' => 'PAYM\'T FOR BROKERAGE CHARGES FOR'],
            ['code' => '014', 'description' => 'PAYM\'T FOR FORWARDING CHARGES FOR'],
            ['code' => '015', 'description' => 'PAYM\'T FOR REIMBURSABLE CHARGES FOR'],
            ['code' => '016', 'description' => 'PAYM\'T FOR FREIGHT. FOR'],
            ['code' => '017', 'description' => 'PAYM\'T FOR BANK CHARGES.'],
            ['code' => '018', 'description' => 'LEGAL FEES FOR'],
            ['code' => '019', 'description' => 'AUDIT FEES FOR'],
            ['code' => '020', 'description' => 'AIR-FARE -'],
            ['code' => '021', 'description' => 'INSURANCE PREMIUM FOR'],
            ['code' => '022', 'description' => 'MEDICINE REIMBURSEMENT.'],
            ['code' => '023', 'description' => 'REPAIR & MAINTENANCE -'],
            ['code' => '024', 'description' => 'ELECTRIC BILLS FOR'],
            ['code' => '025', 'description' => 'WATER CONSUMPTION FOR'],
            ['code' => '026', 'description' => 'GASOLINE CONSUMPTION FOR'],
            ['code' => '027', 'description' => 'TELEPHONE BILLS FOR'],
            ['code' => '028', 'description' => 'PAYM\'T FOR P.O. NO.'],
            ['code' => '029', 'description' => 'CELLPHONE BILLS -'],
            ['code' => '030', 'description' => 'DONATIONS -'],
            ['code' => '031', 'description' => 'EDUCATIONAL ASSITANCE -'],
            ['code' => '032', 'description' => 'BEVERAGE/FOOD SERVED FOR'],
            ['code' => '033', 'description' => 'PARTIAL PAYM\'T FOR PO NO.'],
            ['code' => '034', 'description' => 'FINAL/LAST PAY OF'],
            ['code' => '035', 'description' => 'SEPARATION PAY OF'],
            ['code' => '036', 'description' => 'ROYALTIES FOR'],
            ['code' => '037', 'description' => 'PROFESSIONAL/RETAINER\'S FEE FOR'],
            ['code' => '038', 'description' => 'DIRECTOR\'S FEE FOR'],
            ['code' => '039', 'description' => 'MEMBERSHIP/REGISTRATION FEE FOR'],
            ['code' => '040', 'description' => 'REMITTANCE FOR TAXES -'],
            ['code' => '041', 'description' => 'TRANSFER OF FUND TO'],
            ['code' => '042', 'description' => 'RETENTION FEE.'],
            ['code' => '043', 'description' => 'TRUST FEE FOR'],
            ['code' => '044', 'description' => 'OCCUPATIONAL FEES FOR'],
            ['code' => '045', 'description' => 'RANK & FILE CANTEEN DEDUCTIONS.'],
            ['code' => '046', 'description' => 'RANK & FILE PAYROLL FOR'],
            ['code' => '047', 'description' => 'RANK & FILE UNION DUES.'],
            ['code' => '048', 'description' => 'LOANS'],
            ['code' => '049', 'description' => 'COOP REMITTANCE FOR'],
            ['code' => '050', 'description' => 'LIQUIDATION OF RCA NO.-'],
            ['code' => '051', 'description' => 'REIMBURSEMENT OF OB TRIP TO'],
            ['code' => '052', 'description' => 'REIMBURSEMENT OF CASH PURCHASE.'],
            ['code' => '053', 'description' => 'REIMBURSEMENT OF PROVISIONS'],
            ['code' => '054', 'description' => 'PAYM\'T OF IPO #'],
            ['code' => '055', 'description' => 'REPRESENTATION EXPENSES'],
            ['code' => '056', 'description' => 'SALARY OF CONTRACTUALS'],
            ['code' => '057', 'description' => 'TAXES FEES AND LICENSES'],
            ['code' => '058', 'description' => 'BANK CHARGES'],
            ['code' => '059', 'description' => 'REPLENISHMENT OF PETTY CASH FUND'],
            ['code' => '060', 'description' => 'NEWSPAPER DELIVERY FOR'],
            ['code' => '061', 'description' => 'PAYMENT OF NAMAWU'],
            ['code' => '062', 'description' => 'PAYMENT OF SECURITY SERVICES'],
            ['code' => '063', 'description' => 'REGISTRATION OF COMPANY VEHICLES'],
            ['code' => '064', 'description' => 'SSS MATERNITY BENEFIT'],
            ['code' => '065', 'description' => 'SSS SICKNESS BEENFIT'],
            ['code' => '066', 'description' => 'JANITORIALS SERVICES FOR.'],
            ['code' => '067', 'description' => 'SALARY ALLOTMENT OF'],
            ['code' => '068', 'description' => 'CONSULTANCY FEE FOR'],
            ['code' => '069', 'description' => 'SSS/MED/EC CONTRIBUTION FOR'],
            ['code' => '070', 'description' => 'REIMBURSEMENT OF GAS(LPG) FOR'],
            ['code' => '071', 'description' => 'FULL & FINAL PAYMENT OF'],
            ['code' => '072', 'description' => 'BOWLING TOURNAMENT FEE FOR'],
            ['code' => '073', 'description' => 'CASH ADVANCE'],
            ['code' => '074', 'description' => 'APPRAISAL OF'],
            ['code' => '075', 'description' => 'PHILAMCARE BILIING'],
            ['code' => '076', 'description' => 'SEMINAR FEE RE'],
            ['code' => '077', 'description' => 'ARMORED CAR SERVICES AS PER'],
            ['code' => '078', 'description' => 'PAYMENT OF BILLING FOR'],
            ['code' => '079', 'description' => 'PAYMENT OF CONTRACT BILLING'],
            ['code' => '080', 'description' => 'HDMF CONTRIBUTION FOR'],
            ['code' => '081', 'description' => 'HAZARD FEE FOR'],
            ['code' => '082', 'description' => 'REPLACEMENT OF CANCELLED/STALE CHECKS'],
            ['code' => '083', 'description' => 'REPLACEMENT OF'],
            ['code' => '084', 'description' => 'SEPARATION PAY'],
            ['code' => '085', 'description' => 'MEAL ALLOWANCE FOR'],
            ['code' => '086', 'description' => 'VARIOUS PARKING/TOLL FEES'],
            ['code' => '087', 'description' => 'NOTARIAL FEES FOR'],
            ['code' => '088', 'description' => 'REAL PROPERTY TAX FOR'],
            ['code' => '089', 'description' => 'APSOTEU DUES FOR'],
            ['code' => '090', 'description' => 'UNION DUES FOR'],
            ['code' => '091', 'description' => 'REIMBURSEMENT OF EXPENSES -'],
            ['code' => '092', 'description' => 'RICE SUBSIDY FOR'],
            ['code' => '093', 'description' => 'REFUND OF'],
            ['code' => '094', 'description' => 'MONTHLY OBLIGATION'],
            ['code' => '095', 'description' => 'SHARED COSTS FOR'],
            ['code' => '096', 'description' => 'PHILEX FUNERAL ASSISTANCE'],
            ['code' => '097', 'description' => 'TRAVEL ALLOWANCE'],
            ['code' => '098', 'description' => 'STOCKHLDERS MEETING EXPENSES'],
            ['code' => '099', 'description' => 'PAYMENT OF DEPOSIT FOR'],
            ['code' => '100', 'description' => 'PHILEX MATERNITY ASSISTANCE'],
            ['code' => '101', 'description' => 'BOND DEPOSIT'],
            ['code' => '102', 'description' => 'VARIOUS GOV\'T. FEES'],
            ['code' => '103', 'description' => 'ADVANCE MONTHLY ROYALTY'],
            ['code' => '104', 'description' => 'EARNEST MONEY'],
            ['code' => '105', 'description' => 'HOTEL ACCOMODATION'],
            ['code' => '106', 'description' => 'NET SALARY OF'],
            ['code' => '107', 'description' => 'SSS/EC CONTRIBUTION FOR'],
            ['code' => '108', 'description' => 'MEDICARE CONTRIBUTION FOR'],
            ['code' => '109', 'description' => 'DETENTION CHARGES'],
            ['code' => '110', 'description' => 'PAYMENT OF SUBSCRIPTION FOR'],
            ['code' => '111', 'description' => 'INSURANCE PREMIUM FOR'],
            ['code' => '112', 'description' => 'PER DIEM OF PADCAL CARPENTERS'],
            ['code' => '113', 'description' => 'PER DIEM OF'],
            ['code' => '114', 'description' => 'SOFTWARE SUPPORT CHARGES'],
            ['code' => '115', 'description' => 'PAYMENT OF RENTAL FEES'],
            ['code' => '116', 'description' => '13TH MONTH PAY'],
            ['code' => '117', 'description' => 'CHRISTMAS GIFT THE KIDS FOR YEAR'],
            ['code' => '118', 'description' => 'CHRISTMAS BONUS OF'],
            ['code' => '119', 'description' => 'SICK LEAVE PAYMENT'],
            ['code' => '120', 'description' => 'HOSPITAL BILLS'],
            ['code' => '121', 'description' => 'PAYMENT OF CAPITALIZATION IN CNC'],
            ['code' => '122', 'description' => 'FILING FEE'],
            ['code' => '123', 'description' => 'CASH MONEY'],
            ['code' => '124', 'description' => 'APPLICATION FOR EXPLORATION PERMIT'],
            ['code' => '125', 'description' => 'REGISTRATION FEE'],
            ['code' => '126', 'description' => 'PAYMENT OF PADCAL CARPENTERS PER DIEM'],
            ['code' => '127', 'description' => 'OVERTIME PAY OF'],
            ['code' => '128', 'description' => 'ONE-TIME FINANCIAL ASSISTANCE'],
            ['code' => '129', 'description' => 'AVAILMENT OF CAR PLAN PROGRAM'],
            ['code' => '130', 'description' => 'TRANSPORTATION ALLOWANCE'],
            ['code' => '131', 'description' => 'TRAVEL EXPENSE'],
            ['code' => '132', 'description' => 'FRONT-END'],
            ['code' => '133', 'description' => 'PURCHASE OF BOOK'],
            ['code' => '134', 'description' => 'CUSTOMS DUTIES AND TAXES'],
            ['code' => '135', 'description' => 'FORFEITURE OF DISCOUNT RE:'],
            ['code' => '136', 'description' => 'DEED OF ASSIGNMENT'],
            ['code' => '137', 'description' => 'NAMAWU RAFFLE TICKET'],
            ['code' => '138', 'description' => 'PAYM\'T FOR DANCE INSTRUCTOR'],
            ['code' => '139', 'description' => 'CBA NEGOTIATION'],
            ['code' => '140', 'description' => 'REIMBURSEMENT'],
            ['code' => '141', 'description' => 'ACCEPTANCE FEE'],
            ['code' => '142', 'description' => 'UPDATE SERVICE AGREEMENT RENEWAL'],
            ['code' => '143', 'description' => 'DAMAGE VEHICLE OF'],
            ['code' => '144', 'description' => 'DIRECTORS BONUS'],
            ['code' => '145', 'description' => 'SERVICE FEE'],
            ['code' => '146', 'description' => 'PSE, INC.'],
            ['code' => '147', 'description' => 'AGENCY COMMISSION'],
            ['code' => '148', 'description' => 'COURIER SEERVICES'],
            ['code' => '149', 'description' => 'COURIER/MESSENGERIAL SERVICES'],
            ['code' => '150', 'description' => 'PAYMT. OF REIM/BROK. CHARGES'],
            ['code' => '151', 'description' => 'FREIGHT CHARGES'],
            ['code' => '152', 'description' => 'FOOD CATERING'],
            ['code' => '153', 'description' => 'UMPIRE ANALYSIS'],
            ['code' => '154', 'description' => 'SUBSCRIPTION SHARE AT PAR VALUE'],
            ['code' => '155', 'description' => 'ESCROW FEES'],
            ['code' => '156', 'description' => 'SENIORITY PAY'],
            ['code' => '157', 'description' => 'ISSUANCE FEE'],
            ['code' => '158', 'description' => 'FIREARMS EXPLOSIVES APPLICATION FEES'],
            ['code' => '159', 'description' => 'RETIREMENT PAY OF'],
            ['code' => '160', 'description' => 'CONTRIBUTION TO THE'],
            ['code' => '161', 'description' => 'BOWLING TOURNAMENT'],
            ['code' => '162', 'description' => 'MEDIUM TERM AMORTIZATION'],
            ['code' => '163', 'description' => 'CONTAINER DEPOSIT'],
            ['code' => '164', 'description' => 'HEDGING EXPENSE'],
            ['code' => '165', 'description' => 'NEWSPAPER ADVERTISEMENT'],
            ['code' => '166', 'description' => 'ADDITIONAL BENEFITS'],
            ['code' => '167', 'description' => 'TRAINING EXPENSES'],
            ['code' => '168', 'description' => 'TRAINING FEE'],
            ['code' => '169', 'description' => 'HONORARIUM'],
            ['code' => '170', 'description' => 'CONTRACT SALARY'],
            ['code' => '171', 'description' => 'BOARD OF DIRECTORS'],
            ['code' => '172', 'description' => 'PARTNERS SHARE'],
            ['code' => '173', 'description' => 'REPRESENTATION AND LEGAL'],
            ['code' => '174', 'description' => 'AMORTIZATION OF'],
            ['code' => '175', 'description' => 'HONORARIUM'],
            ['code' => '176', 'description' => 'RETAINER\'S FEE'],
            ['code' => '177', 'description' => 'TAX DEFICIENCY'],
            ['code' => '178', 'description' => 'TAX LIABILITY'],
            ['code' => '179', 'description' => 'SURIGAO MEDICAL'],
            ['code' => '180', 'description' => 'OUT OF POCKET EXPENSES'],
            ['code' => '181', 'description' => 'SALE OF USED EQUIPMENT'],
            ['code' => '182', 'description' => 'MISCELLANEOUS EXPENSES'],
            ['code' => '183', 'description' => 'PURCHASE OF TRANSPORTATION EQUIPMENT'],
            ['code' => '184', 'description' => 'PURCH OF TRANS EQPT'],
            ['code' => '185', 'description' => 'MANPOWER SERVICES'],
            ['code' => '186', 'description' => 'ESTABLISHMENT FEE'],
            ['code' => '187', 'description' => 'CORPORATE TAX PAYABLE'],
            ['code' => '188', 'description' => 'LITIGATION EXPENSES'],
            ['code' => '189', 'description' => 'INVESTMENT IN SHARES'],
            ['code' => '190', 'description' => 'MONEY MARKET PLACEMENT'],
            ['code' => '191', 'description' => 'CONVERSION OF US$ TO PESO'],
            ['code' => '192', 'description' => 'PURCHASE OF SERVICE CAR'],
            ['code' => '193', 'description' => 'REVOLVING FUND'],
            ['code' => '194', 'description' => 'PARTICIPATION IN'],
            ['code' => '195', 'description' => 'RENEWAL FEE'],
            ['code' => '196', 'description' => 'PAYMENT OF SUBSCRIPTION PAYABLE'],
            ['code' => '197', 'description' => 'FRONT-END MONEY'],
            ['code' => '198', 'description' => 'VISA FEE'],
            ['code' => '199', 'description' => 'OB MONEY'],
            ['code' => '200', 'description' => 'BANK CHARGES ON LOANS'],
            ['code' => '201', 'description' => 'PAYMENT OF DIVIDENDS'],
            ['code' => '202', 'description' => 'PAYMENT OF DIVIDEND'],
            ['code' => '203', 'description' => 'PGI ACCOUNTS'],
            ['code' => '204', 'description' => 'PURCHASE OF PHILEX SHARES'],
            ['code' => '205', 'description' => 'CAR PLAN / CAR LOAN'],
            ['code' => '206', 'description' => 'VISA APPLICATION'],
            ['code' => '207', 'description' => 'FOR THE ACCOUNT OF PGPI'],
            ['code' => '208', 'description' => 'SHARES BUYBACK'],
            ['code' => '209', 'description' => 'COMPENSATION'],
            ['code' => '210', 'description' => 'LAND BANKING PROJECT'],
            ['code' => '211', 'description' => 'ADVANCES'],
            ['code' => '212', 'description' => 'PAYMENT'],
            ['code' => '213', 'description' => 'OFFICE RELOCATION'],
            ['code' => '214', 'description' => 'ACCIDENT BENEFIT INSURANCE'],
            ['code' => '215', 'description' => 'FINAL CLAIM'],
            ['code' => '216', 'description' => 'GOLD BULLION SHIPMENT EXPENSES'],
        ];

        foreach ($descriptions as $description) {
            SharedDescription::create($description);
        }
    }
}
