export type Permission =
    | 'rfp-request-list'
    | 'rfp-request-create'
    | 'rfp-request-edit'
    | 'rfp-request-delete'
    | 'rfp-category-list'
    | 'rfp-category-create'
    | 'rfp-category-edit'
    | 'rfp-category-delete'
    | 'rfp-usage-list'
    | 'rfp-usage-create'
    | 'rfp-usage-edit'
    | 'rfp-usage-delete'
    | 'rfp-currency-list'
    | 'rfp-currency-create'
    | 'rfp-currency-edit'
    | 'rfp-currency-delete'
    | 'sap-supplier-list';
